apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: iaf-group
  namespace: iaf
spec:
  targetNamespaces:
  - iaf 
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-automation
  namespace: iaf
spec:
  channel: v1.0
  installPlanApproval: Automatic
  name: ibm-automation
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
